# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nego_ads_drf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_controller', models.TextField(blank=True, max_length=100, null=True, verbose_name='buying_controller')),
                ('buyer', models.TextField(blank=True, max_length=100, null=True, verbose_name='buyer')),
                ('junior_buyer', models.TextField(blank=True, max_length=100, null=True, verbose_name='junior_buyer')),
                ('brand_indicator', models.TextField(blank=True, max_length=100, null=True, verbose_name='brand_indicator')),
                ('brand_name', models.TextField(blank=True, max_length=100, null=True, verbose_name='brand_name')),
                ('product_sub_group_code', models.TextField(blank=True, max_length=100, null=True, verbose_name='product_sub_group_code')),
                ('product_sub_group_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='product_sub_group_description')),
                ('base_product_number', models.IntegerField(blank=True, null=True, verbose_name='base_product_number')),
                ('long_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='long_description')),
                ('store_type', models.TextField(blank=True, max_length=100, null=True, verbose_name='store_type')),
                ('store_count', models.IntegerField(blank=True, null=True, verbose_name='store_count')),
                ('subs_count', models.IntegerField(blank=True, null=True, verbose_name='subs_count')),
                ('sales_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='sales_value')),
                ('sales_volume', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='sales_volume')),
                ('cogs_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='cogs_value')),
                ('rsp', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, verbose_name='rsp')),
                ('cgm_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='cgm_value')),
                ('need_state', models.TextField(blank=True, max_length=100, null=True, verbose_name='need_state')),
                ('time_period', models.TextField(blank=True, max_length=100, null=True, verbose_name='time_period')),
                ('cps', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='cps')),
                ('pps', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='pps')),
                ('rate_of_sale', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='rate_of_sale')),
                ('cps_quartile', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='cps_quartile')),
                ('pps_quartile', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='pps_quartile')),
                ('performance_quartile', models.TextField(blank=True, max_length=100, null=True, verbose_name='performance_quartile')),
            ],
        ),
        migrations.CreateModel(
            name='outperformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_director', models.TextField(blank=True, max_length=100, null=True, verbose_name='category_director')),
                ('buying_controller', models.TextField(blank=True, max_length=100, null=True, verbose_name='buying_controller')),
                ('buyer', models.TextField(blank=True, max_length=100, null=True, verbose_name='buyer')),
                ('junior_buyer', models.TextField(blank=True, max_length=100, null=True, verbose_name='junior_buyer')),
                ('product_sub_group_code', models.TextField(blank=True, max_length=100, null=True, verbose_name='product_sub_group_code')),
                ('week_flag', models.TextField(blank=True, max_length=100, null=True, verbose_name='output_date')),
                ('update_date', models.DateField(verbose_name='update_date')),
                ('week_number', models.IntegerField(blank=True, null=True, verbose_name='week_number')),
                ('tesco_outperformanc_percentage', models.DecimalField(decimal_places=10, default=0.0, max_digits=20, verbose_name='tesco_outperformanc_percentage')),
                ('tesco_outperformanc_unit_prcnt', models.DecimalField(decimal_places=10, default=0.0, max_digits=20, verbose_name='tesco_outperformanc_unit_prcnt')),
                ('product_sub_group_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='product_sub_group_description')),
            ],
        ),
        migrations.CreateModel(
            name='pricebucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sub_group_code', models.TextField(blank=True, max_length=100, null=True, verbose_name='product_sub_group_code')),
                ('category_director', models.TextField(blank=True, max_length=100, null=True, verbose_name='category_director')),
                ('buying_controller', models.TextField(blank=True, max_length=100, null=True, verbose_name='buying_controller')),
                ('buyer', models.TextField(blank=True, max_length=100, null=True, verbose_name='buyer')),
                ('junior_buyer', models.TextField(blank=True, max_length=100, null=True, verbose_name='junior_buyer')),
                ('retailer', models.TextField(blank=True, max_length=100, null=True, verbose_name='retailer')),
                ('week_flag', models.TextField(blank=True, max_length=100, null=True, verbose_name='week_flag')),
                ('sku', models.IntegerField(blank=True, null=True, verbose_name='sku')),
                ('sku_gravity', models.IntegerField(blank=True, null=True, verbose_name='sku_gravity')),
                ('product_sub_group_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='product_sub_group_description')),
                ('price_gravity', models.TextField(blank=True, max_length=100, null=True, verbose_name='price_gravity')),
            ],
        ),
        migrations.CreateModel(
            name='unmatchedprod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_id', models.IntegerField(blank=True, null=True, verbose_name='competitor_id')),
                ('competitor_product_sid', models.IntegerField(blank=True, null=True, verbose_name='competitor_product_sid')),
                ('week_flag', models.TextField(blank=True, max_length=100, null=True, verbose_name='week_flag')),
                ('product_sub_group_code', models.TextField(blank=True, max_length=100, null=True, verbose_name='product_sub_group_code')),
                ('category_director', models.TextField(blank=True, max_length=100, null=True, verbose_name='category_director')),
                ('buying_controller', models.TextField(blank=True, max_length=100, null=True, verbose_name='buying_controller')),
                ('buyer', models.TextField(blank=True, max_length=100, null=True, verbose_name='buyer')),
                ('junior_buyer', models.TextField(blank=True, max_length=100, null=True, verbose_name='junior_buyer')),
                ('product_sub_group_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='product_sub_group_description')),
                ('retailer', models.TextField(blank=True, max_length=100, null=True, verbose_name='retailer')),
                ('competitor_product_desc', models.TextField(blank=True, max_length=100, null=True, verbose_name='competitor_product_desc')),
                ('asp', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='asp')),
            ],
        ),
    ]
